# Generated by Django 5.2.1 on 2025-06-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_prompt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
