# Generated by Django 5.2.1 on 2025-05-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('정치', '정치'), ('경제', '경제'), ('사회', '사회'), ('문화', '문화'), ('국제', '국제'), ('지역', '지역'), ('스포츠', '스포츠'), ('IT과학', 'IT과학')], max_length=20)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('칼럼', '칼럼'), ('분석글', '분석글'), ('에세이', '에세이'), ('시', '시')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='prompts.issue')),
            ],
        ),
    ]
