# Generated by Django 5.2.1 on 2025-06-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('송사리 (3-4cm)', '송사리 (3-4cm)'), ('전어 (20-25cm)', '전어 (20-25cm)'), ('도미 (40-60cm)', '도미 (40-60cm)'), ('참치 (100-250cm)', '참치 (100-250cm)'), ('고래 (15-30m)', '고래 (15-30m)')], max_length=20, unique=True)),
                ('min_posts', models.IntegerField(help_text='이 등급이 되기 위한 최소 발행글 수')),
                ('max_posts', models.IntegerField(blank=True, help_text='이 등급의 최대 발행글 수 (다음 등급 전까지)', null=True)),
                ('image_path', models.CharField(help_text='등급별 이미지 경로', max_length=100)),
                ('description', models.TextField(blank=True, help_text='등급에 대한 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_posts'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('result_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
