# Generated by Django 5.2.3 on 2025-06-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_mypick'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('result_text', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
