# Generated by Django 5.2.1 on 2025-06-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
