# Generated by Django 5.2.1 on 2025-06-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='credit',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
