# Generated by Django 5.2.1 on 2025-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizing', '0002_item_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='part_code',
            field=models.IntegerField(choices=[(1, '몸체'), (2, '가방'), (3, '안경'), (4, '모자'), (5, '악세사리'), (6, '옷')]),
        ),
    ]
